/**
 * Do not edit directly
 * Generated on Thu, 25 Nov 2021 14:41:29 GMT
 */

module.exports = {
  "defaut-palette-50": "#fafcfc",
  "defaut-palette-100": "#e4e8ee",
  "defaut-palette-200": "#c1c9d0",
  "defaut-palette-300": "#a2abb7",
  "defaut-palette-400": "#8892A2",
  "defaut-palette-500": "#6b7385",
  "defaut-palette-600": "#505669",
  "defaut-palette-700": "#3c4055",
  "defaut-palette-800": "#36384D",
  "defaut-palette-900": "#2b2e44",
  "accent-palette-50": "#EFFCFD",
  "accent-palette-100": "#CFF4FA",
  "accent-palette-200": "#80E3F2",
  "accent-palette-300": "#25CDE6",
  "accent-palette-400": "#20B4CA",
  "accent-palette-500": "#1DA1B5",
  "accent-palette-600": "#167D8C",
  "accent-palette-700": "#136875",
  "accent-palette-800": "#0F535D",
  "accent-palette-900": "#0C4149",
  "font-family": "Graphik LC",
  "succes-palette-50": "#E7F9F0",
  "succes-palette-100": "#CFF3E1",
  "succes-palette-200": "#6EDAA4",
  "succes-palette-300": "#3DCE86",
  "succes-palette-400": "#0DC268",
  "succes-palette-500": "#0A9B53",
  "succes-palette-600": "#087C42",
  "succes-palette-700": "#065D32",
  "succes-palette-800": "#054726",
  "succes-palette-900": "#04351C",
  "fontsize-g": "64px",
  "fontsize-xxl": "56px",
  "fontsize-xl": "48px",
  "fontsize-l": "36px",
  "fontsize-lm": "28px",
  "fontsize-ms": "20px",
  "fontsize-s": "16px",
  "fontsize-xs": "14px",
  "fontsize-xxs": "12px",
  "fontsize-m": "24px",
  "fontweight-semibold": "Semibold",
  "fontweight-medium": "Medium",
  "fontweight-regular": "Regular",
  "line-height-text": "140%",
  "line-height-interface": "110%",
  "header-display-font-family": "Graphik LC",
  "header-display-font-weight": "Medium",
  "header-display-line-height": "110%",
  "header-display-font-size": "36px",
  "header-display-letter-spacing": "0",
  "header-display-paragraph-spacing": "0",
  "header-display-text-decoration": "0",
  "header-display-text-case": "0",
  "header-h1-font-family": "Graphik LC",
  "header-h1-font-weight": "Medium",
  "header-h1-line-height": "110%",
  "header-h1-font-size": "28px",
  "header-h1-letter-spacing": "0",
  "header-h1-paragraph-spacing": "0",
  "header-h1-text-decoration": "0",
  "header-h1-text-case": "0",
  "header-h2-font-family": "Graphik LC",
  "header-h2-font-weight": "Medium",
  "header-h2-line-height": "110%",
  "header-h2-font-size": "24px",
  "header-h2-letter-spacing": "0",
  "header-h2-paragraph-spacing": "0",
  "header-h2-text-decoration": "0",
  "header-h2-text-case": "0",
  "header-h3-font-family": "Graphik LC",
  "header-h3-font-weight": "Medium",
  "header-h3-line-height": "110%",
  "header-h3-font-size": "20px",
  "header-h3-letter-spacing": "0",
  "header-h3-paragraph-spacing": "0",
  "header-h3-text-decoration": "0",
  "header-h3-text-case": "0",
  "header-h4-font-family": "Graphik LC",
  "header-h4-font-weight": "Medium",
  "header-h4-line-height": "110%",
  "header-h4-font-size": "12px",
  "header-h4-letter-spacing": "0",
  "header-h4-paragraph-spacing": "0",
  "header-h4-text-decoration": "0",
  "header-h4-text-case": "uppercase",
  "header-base-text-font-family": "Graphik LC",
  "header-base-text-font-weight": "Regular",
  "header-base-text-line-height": "110%",
  "header-base-text-font-size": "16px",
  "header-base-text-letter-spacing": "0",
  "header-base-text-paragraph-spacing": "0",
  "header-base-text-text-decoration": "0",
  "header-base-text-text-case": "0",
  "header-secondary-text-font-family": "Graphik LC",
  "header-secondary-text-font-weight": "Regular",
  "header-secondary-text-line-height": "110%",
  "header-secondary-text-font-size": "14px",
  "header-secondary-text-letter-spacing": "0",
  "header-secondary-text-paragraph-spacing": "0",
  "header-secondary-text-text-decoration": "0",
  "header-secondary-text-text-case": "0",
  "input-label-font-family": "Graphik LC",
  "input-label-font-weight": "Medium",
  "input-label-line-height": "110%",
  "input-label-font-size": "16px",
  "input-label-letter-spacing": "0",
  "input-label-paragraph-spacing": "0",
  "input-label-text-decoration": "0",
  "input-label-text-case": "0",
  "input-text-font-family": "Graphik LC",
  "input-text-font-weight": "Regular",
  "input-text-line-height": "110%",
  "input-text-font-size": "16px",
  "input-text-letter-spacing": "0",
  "input-text-paragraph-spacing": "0",
  "input-text-text-decoration": "0",
  "input-text-text-case": "0",
  "input-error-subscription-font-family": "Graphik LC",
  "input-error-subscription-font-weight": "Regular",
  "input-error-subscription-line-height": "110%",
  "input-error-subscription-font-size": "14px",
  "input-error-subscription-letter-spacing": "0",
  "input-error-subscription-paragraph-spacing": "0",
  "input-error-subscription-text-decoration": "0",
  "input-error-subscription-text-case": "0",
  "button-s-text-font-family": "Graphik LC",
  "button-s-text-font-weight": "Regular",
  "button-s-text-line-height": "110%",
  "button-s-text-font-size": "16px",
  "button-s-text-letter-spacing": "0",
  "button-s-text-paragraph-spacing": "0",
  "button-s-text-text-decoration": "0",
  "button-s-text-text-case": "0",
  "button-xs-text-font-family": "Graphik LC",
  "button-xs-text-font-weight": "Regular",
  "button-xs-text-line-height": "110%",
  "button-xs-text-font-size": "14px",
  "button-xs-text-letter-spacing": "0",
  "button-xs-text-paragraph-spacing": "0",
  "button-xs-text-text-decoration": "0",
  "button-xs-text-text-case": "0",
  "space-xl": "64px",
  "space-l": "48px",
  "space-m": "32px",
  "space-sm": "24px",
  "space-s": "16px",
  "space-xs": "8px",
  "space-xxs": "4px",
  "space-no": "0px",
  "input-height-s": "36px",
  "input-height-m": "42px",
  "input-height-xs": "28px",
  "xxxs": "2px",
  "error-palette-50": "#F9E6EA",
  "error-palette-100": "#F3CED5",
  "error-palette-200": "#E69DAB",
  "error-palette-300": "#DA6C80",
  "error-palette-400": "#CE3B57",
  "error-palette-500": "#C10A2C",
  "error-palette-600": "#9A0823",
  "error-palette-700": "#74061A",
  "error-palette-800": "#4D0412",
  "error-palette-900": "#270209",
  "base-palette-white": "#ffffff",
  "uppercase": "uppercase",
  "radius-no": "0px",
  "radius-xs": "4px",
  "radius-s": "8px",
  "radius-m": "16px",
  "radius-round": "100px",
  "shadow-modal": "0px 10px 50px 0px #DFE0E3",
  "shadow-dropdown": "0px 0px 15px 0px #DFE0E3",
  "accent-color-text": "#1DA1B5",
  "accent-color-text-secondary": "#20B4CA",
  "accent-color-bg": "#CFF4FA",
  "accent-color-cta": "#1DA1B5",
  "accent-color-cta-hover": "#136875",
  "accent-color-cta-disabled": "#CFF4FA",
  "accent-color-icon": "#1DA1B5",
  "accent-color-icon-secondary": "#20B4CA",
  "accent-border-active": "#1DA1B5",
  "accent-border-focus": "#1DA1B5",
  "accent-border-hover": "#167D8C",
  "default-color-text": "#3c4055",
  "default-color-text-secondary": "#a2abb7",
  "default-color-bg": "#ffffff",
  "default-color-bg-secondary": "#fafcfc",
  "default-color-cta": "#3c4055",
  "default-color-cta-hover": "#2b2e44",
  "default-color-cta-disabled": "#8892A2",
  "default-color-icon": "#3c4055",
  "default-color-icon-secondary": "#c1c9d0",
  "default-color-divider": "#e4e8ee",
  "default-color-border": "#e4e8ee",
  "default-color-border-hover": "#c1c9d0",
  "default-color-text-disabled": "#e4e8ee",
  "default-color-secondary": "#c1c9d0",
  "default-color-secondary-hover": "#8892A2",
  "default-color-secondary-disabled": "#e4e8ee",
  "error-color-text": "#C10A2C",
  "error-color-bg": "#F3CED5",
  "error-color-cta": "#C10A2C",
  "error-color-cta-hover": "#9A0823",
  "error-color-cta-disabled": "#F3CED5",
  "error-color-icon": "#C10A2C",
  "error-border-active": "#C10A2C",
  "success-color-text": "#0A9B53",
  "success-color-bg": "#CFF3E1",
  "success-color-cta": "#0A9B53",
  "success-color-cta-hover": "#087C42",
  "success-color-cta-disabled": "#CFF3E1",
  "success-color-icon": "#0A9B53",
  "success-border-active": "#0A9B53"
};